# Generated by Django 4.2.7 on 2023-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='creat_at',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
