# Generated by Django 4.2.7 on 2023-11-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_news_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='caregory',
            new_name='category',
        ),
    ]
