# Generated by Django 4.2.7 on 2023-11-18 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_contactpersonal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPersonal',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
