# Generated by Django 4.2.7 on 2023-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_news_is_active_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='home.tags'),
        ),
    ]
